### ISSUE TITLE
Registro de horas

### ISSUE THREAD

**Issue by antjim** [SOS-2016-05/SOS-2016-05#10]
Es importante no olvidar el registro de horas.

*_> Tener un número total de horas invertidas entre el día 22 de Febrero y el 1 de Marzo de, al menos, 2 horas. *_

**Comment by antjim** [comment]
Esta tarea es común.

**Comment by enrguefer** [comment]
Se han invertido un total de 10 horas y 42 minutos entre todos los integrantes del grupo
